trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: Build
    steps:
      - task: CopyFiles@2
        inputs:
          Contents: |
            *.html
            scripts/*.js
            css/*.css
          TargetFolder: build
        displayName: 'Copy files to deploy'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: build
          includeRootFolder: false
          archiveType: zip
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildId).zip'
        displayName: 'Create deployment archive'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.Repository.Name)-$(Build.BuildId).zip'
          ArtifactName: personal-domain
        displayName: 'Publish artifact: $(Build.Repository.Name)'
